--CONST PLAYER
CONST_MAX_HP_PLAYER = 80
CONST_REGEN_PLAYER = 0 
CONST_VAMPIR = 0 
CONST_DAMAGE_BULLET = 8
CONST_DAMAGE_UNIT = 30
CONST_CRITICAL = 3 
CONST_ARMOR = 3 
CONST_UKLON_PLAYER = 3 
CONST_SPEED_PLAYER = 80
CONST_SPEED_SHOOT = 0.8 
-- AK47
CONST_TIME_SHOOT_AK47 = 1 
CONST_KNIFE_DAMAGE = 15
CONST_TIME_KNIFE = 1.5 
CONST_KOL_PROBITIE = 0
CONST_HEADSHOT = 0 


MAX_REGEN_PLAYER = 0 -- /10 max 30
-- MAX CHAR PLAYER
MAX_VAMPIR = 9 -- % max 9
MAX_CRITICAL = 30
MAX_ARMOR = 30   -- %
MAX_UKLON_PLAYER = 30 -- max 30 %
MAX_SPEED_PLAYER = 100
MAX_SPEED_SHOOT = 0.29 -- sekunda - max 0.2
-- AK47 and KNIFE
MAX_TIME_SHOOT_AK47 = 0.5 -- max 0.3
MAX_TIME_KNIFE = 0.8 -- max 1 sek
MAX_KOL_PROBITIE = 2
--------