require "elements_game.core.globals"

local time = 0
local second = 0

function update(self, dt)
	time = time + dt
	local minuta = time / 60
	second = second + dt
	if second > 60 then
		second = 0
	end
	local format = string.format("%02d:%02d", minuta ,second)
	label.set_text("#label", format)
	if LANG_RUS then
		label.set_text("#level_label", "уровень " .. LEVEL)
	else
		label.set_text("#level_label", "level " .. LEVEL)
	end
end